---
name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          lfs: true
          fetch-depth: 0
      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "21.x"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --frozen-lockfile
      - name: "Build"
        run: yarn build
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          directory: "build"
          filename: "release.zip"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Release Build"
          files: |
            build/release.zip
